In [5]:
#Polynomial Feature Creation Example
from numpy import asarray
from sklearn.preprocessing import PolynomialFeatures
# define the dataset
data = asarray([[2,3],[4,5],[6,7]])
print(data)

[[2 3]
 [4 5]
 [6 7]]


In [6]:
# perform a polynomial features transform of the dataset
trans = PolynomialFeatures(degree=2)
data = trans.fit_transform(data)
print(data)

[[ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]
 [ 1.  6.  7. 36. 42. 49.]]


In [9]:
data = asarray([[2,3],[4,5],[6,7]])

In [10]:
# perform a polynomial features transform of the dataset with only interaction terms
trans = PolynomialFeatures(degree=2,interaction_only=True,include_bias=False)
data = trans.fit_transform(data)
print(data)

[[ 2.  3.  6.]
 [ 4.  5. 20.]
 [ 6.  7. 42.]]
