In [2]:
import pandas as pd
import numpy as np

In [3]:
print("Hello World")

Hello World


In [4]:
lst = [1,2,3]
print(lst)

[1, 2, 3]


In [5]:
arr = np.array([lst,lst])

In [6]:
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [8]:
arr.shape

(2, 3)

In [13]:
np.sum(arr,axis=0)   # Along rows

array([2, 4, 6])

In [14]:
np.sum(arr,axis=1)   # Along columns

array([6, 6])

In [20]:
# Help 1 - Shift + Tab
np.sum(arr)

12

In [17]:
help(np.mean)

Help on function mean in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For integer inputs,