In [1]:
import pandas as pd
import numpy as np

## Datatypes

In [3]:
bool(1)

True

In [4]:
float('2')

2.0

In [5]:
int(2.0)

2

In [6]:
s = 'sahil'
print(type(s))

<class 'str'>


In [8]:
#Revese String
s[::-1]

'lihas'

In [7]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [4]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Data Types in Python

In [16]:
py_l = [i for i in range(100000)]

In [17]:
len(py_l)

100000

In [18]:
py_l[:5]

[0, 1, 2, 3, 4]

In [21]:
%%timeit
#global py_l
py_l1 = [i*2 for i in py_l]

4.48 ms ± 123 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Dictionary

In [9]:
dict1 = {
    "id":1,
    "name":"sahil",
    "country":"canada"
}

In [11]:
dict1["id"]

1

### Tuple

In [22]:
tple = (1,2,3,4,5)

In [23]:
tple[3]=1

TypeError: 'tuple' object does not support item assignment

### Sets

In [7]:
s1 = {1,2,3,4,4}
s2 = {3,4,5,6}

In [15]:
s1 & s2                                                      # |(union) &(intersect)

{3, 4}

## Numpy

In [22]:
arr = np.array([i for i in range(100000)])

In [23]:
%%timeit
arr2 = arr*2

36.7 µs ± 556 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [24]:
arr[:5]

array([0, 1, 2, 3, 4])

In [27]:
##Allows broadcasting
arr[:5] + 1

array([1, 2, 3, 4, 5])

## Dataframes

In [28]:
dicttotal = {
    "id":[1,2,3],
    "name":["sahil","abc","xyz"],
    "country":["canada","usa","india"]
}
dicttotal

{'id': [1, 2, 3],
 'name': ['sahil', 'abc', 'xyz'],
 'country': ['canada', 'usa', 'india']}

In [29]:
df1 = pd.DataFrame(dicttotal)

In [30]:
df1

id   name country
0   1  sahil  canada
1   2    abc     usa
2   3    xyz   india

In [31]:
df2 = pd.DataFrame({
    "id":[1,2],
    "jobrole":["data scientist","data engineer"]
})
df2

id         jobrole
0   1  data scientist
1   2   data engineer

In [32]:
## Example of Merge

In [33]:
pd.merge(df1,df2,how='left',left_on='id',right_on='id')    #Outer, Right, Left

id   name country         jobrole
0   1  sahil  canada  data scientist
1   2    abc     usa   data engineer
2   3    xyz   india             NaN